name: Overwrite some file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt    
      - name: Commit & Push
        run: |
          git config --global user.name 'Juan Guillermo Palma Ceron'
          git config --global user.email 'juanpalma@bcp.com.pe'
          git add .
          git commit -m "Automated report"
          git push
