name: Overwrite some file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite file
        uses: "testjuanpalma/repo-template@main"
        with:
          path: ci/test-output/out.js
          write-mode: overwrite
          contents: |
            console.log('some contents')
            
      - name: Commit & Push
        run: |
          git config --global user.name 'Juan Guillermo Palma Ceron'
          git config --global user.email 'juanpalma@bcp.com.pe'
          git commit -am "Automated report"
          git push
