name: gpgsignedcommits

on:
  push:
    branches: [main]

jobs:
  sign-commit:
    runs-on: ubuntu-latest
#    container: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GPG action import
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
#      - name: Node build and push 
#        run: |
#          node --version
#          npm --version
#          npm install
#          node app.js
#          npm run release -- --increment ${{github.event.inputs.releaseCanditateVersion}} -V
#          npm publish
#      - name: Sign commit and push changes
#        run: |
#          git add .
#          git commit -S -m "This commit is signed!"
#          git push origin ${{ env.REPO_NAME }} --force
