name: Overwrite some file

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Import bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Create report file
        run: date +%s > report.txt
      - name: Update version
        id: version
        run: |
          echo "GITHUB_REF is a tag you set for the release"
          echo "Your GitHub ref: ${GITHUB_REF}"
          VERSION=`echo "${GITHUB_REF}" | cut -f 3 -d "/"`
          echo "Preparing version ${VERSION}"
          echo "__version__ = \"${VERSION}\"" > __version__.py
          echo "##[set-output name=version;]$(echo ${VERSION})"
      - name: Test
        run: |
          echo $texttest
        env:
          texttest: ${{ secrets.TEST_SECRET }}
      - name: Commit & Push
        run: |
          git commit -m "Automated report"
          env:
            GITHUB_TOKEN: ${{ secrets.OSLASH_BOT_GITHUB_TOKEN }}
            GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
            GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
            GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
            GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
